DROP TABLE IF EXISTS `achievements`;
CREATE TABLE `achievements` (
    StudentID mediumint(9),
    
    QuizMaster tinyint(1) NOT NULL DEFAULT 0,
    AllSnapFacts tinyint(1) NOT NULL DEFAULT 0,
    ResourcePage tinyint(1) NOT NULL DEFAULT 0,
    QuizLeaderBoardTopTenOnce tinyint(1) NOT NULL DEFAULT 0,
    LearningFromMistakes tinyint(1) NOT NULL DEFAULT 0,
    HeadOfClass tinyint(1) NOT NULL DEFAULT 0,
    WeeklyGenius tinyint(1) NOT NULL DEFAULT 0,
    GotItRight tinyint(1) NOT NULL DEFAULT 0,
    Aced tinyint(1) NOT NULL DEFAULT 0,
    HatTrick tinyint(1) NOT NULL DEFAULT 0,
    MasterExtraContent tinyint(1) NOT NULL DEFAULT 0,
    LoginMaster tinyint(1) NOT NULL DEFAULT 0,
    LoginWeek1 tinyint(1) NOT NULL DEFAULT 0,
    LoginWeek2 tinyint(1) NOT NULL DEFAULT 0,
    LoginWeek3 tinyint(1) NOT NULL DEFAULT 0,
    LoginWeek4 tinyint(1) NOT NULL DEFAULT 0,
    LoginWeek5 tinyint(1) NOT NULL DEFAULT 0,
    LoginWeek6 tinyint(1) NOT NULL DEFAULT 0,
    LoginWeek7 tinyint(1) NOT NULL DEFAULT 0,
    LoginWeek8 tinyint(1) NOT NULL DEFAULT 0,
    LoginWeek9 tinyint(1) NOT NULL DEFAULT 0,
    LoginWeek10 tinyint(1) NOT NULL DEFAULT 0,
    MasterGaming tinyint(1) NOT NULL DEFAULT 0,
    LaunchSportsNinja tinyint(1) NOT NULL DEFAULT 0,
    PlayEveryGameModeSn tinyint(1) NOT NULL DEFAULT 0,
    BeatScoreSnA tinyint(1) NOT NULL DEFAULT 0,
    BeatScoreSnB tinyint(1) NOT NULL DEFAULT 0,
    BeatScoreSnC tinyint(1) NOT NULL DEFAULT 0,
    LaunchMealCrusher tinyint(1) NOT NULL DEFAULT 0,
    PlayEveryGameModeMc tinyint(1) NOT NULL DEFAULT 0,
    BeatScoreMcA tinyint(1) NOT NULL DEFAULT 0,
    BeatScoreMcB tinyint(1) NOT NULL DEFAULT 0,
    BeatScoreMcC tinyint(1) NOT NULL DEFAULT 0,
    
    PRIMARY KEY(StudentID),
    FOREIGN KEY (StudentID) REFERENCES student(StudentID)
) ENGINE=INNODB;
