DROP TABLE IF EXISTS `achievements`;
CREATE TABLE `achievements` (
    StudentID mediumint(9),
    
    QuizMaster tinyint(1) NOT NULL DEFAULT 0,
    AllSnapFacts tinyint(1) NOT NULL DEFAULT 0,
    ResourcePage tinyint(1) NOT NULL DEFAULT 0,
    QuizLeaderBoardTopTenOnce tinyint(1) NOT NULL DEFAULT 0,
    LearningFromMistakes tinyint(1) NOT NULL DEFAULT 0,
    HeadOfClass tinyint(1) NOT NULL DEFAULT 0,
    WeeklyGenius tinyint(1) NOT NULL DEFAULT 0,
    GotItRight tinyint(1) NOT NULL DEFAULT 0,
    Aced tinyint(1) NOT NULL DEFAULT 0,
    HatTrick tinyint(1) NOT NULL DEFAULT 0,
    MasterExtraContent tinyint(1) NOT NULL DEFAULT 0,
    LoginMaster tinyint(1) NOT NULL DEFAULT 0,
    LoginWeek1 tinyint(1) NOT NULL DEFAULT 0,
    LoginWeek2 tinyint(1) NOT NULL DEFAULT 0,
    LoginWeek3 tinyint(1) NOT NULL DEFAULT 0,
    LoginWeek4 tinyint(1) NOT NULL DEFAULT 0,
    LoginWeek5 tinyint(1) NOT NULL DEFAULT 0,
    LoginWeek6 tinyint(1) NOT NULL DEFAULT 0,
    LoginWeek7 tinyint(1) NOT NULL DEFAULT 0,
    LoginWeek8 tinyint(1) NOT NULL DEFAULT 0,
    LoginWeek9 tinyint(1) NOT NULL DEFAULT 0,
    LoginWeek10 tinyint(1) NOT NULL DEFAULT 0,
    MasterGaming tinyint(1) NOT NULL DEFAULT 0,
    LaunchSportsNinja tinyint(1) NOT NULL DEFAULT 0,
    PlayEveryGameModeSn tinyint(1) NOT NULL DEFAULT 0,
    BeatScoreSnA tinyint(1) NOT NULL DEFAULT 0,
    BeatScoreSnB tinyint(1) NOT NULL DEFAULT 0,
    BeatScoreSnC tinyint(1) NOT NULL DEFAULT 0,
    LaunchMealCrusher tinyint(1) NOT NULL DEFAULT 0,
    PlayEveryGameModeMc tinyint(1) NOT NULL DEFAULT 0,
    BeatScoreMcA tinyint(1) NOT NULL DEFAULT 0,
    BeatScoreMcB tinyint(1) NOT NULL DEFAULT 0,
    BeatScoreMcC tinyint(1) NOT NULL DEFAULT 0,
    
    QuizMasterViewed tinyint(1) NOT NULL DEFAULT 0,
    AllSnapFactsViewed tinyint(1) NOT NULL DEFAULT 0,
    ResourcePageViewed tinyint(1) NOT NULL DEFAULT 0,
    QuizLeaderBoardTopTenOnceViewed tinyint(1) NOT NULL DEFAULT 0,
    LearningFromMistakesViewed tinyint(1) NOT NULL DEFAULT 0,
    HeadOfClassViewed tinyint(1) NOT NULL DEFAULT 0,
    WeeklyGeniusViewed tinyint(1) NOT NULL DEFAULT 0,
    GotItRightViewed tinyint(1) NOT NULL DEFAULT 0,
    AcedViewed tinyint(1) NOT NULL DEFAULT 0,
    HatTrickViewed tinyint(1) NOT NULL DEFAULT 0,
    MasterExtraContentViewed tinyint(1) NOT NULL DEFAULT 0,
    LoginMasterViewed tinyint(1) NOT NULL DEFAULT 0,
    LoginWeek1Viewed tinyint(1) NOT NULL DEFAULT 0,
    LoginWeek2Viewed tinyint(1) NOT NULL DEFAULT 0,
    LoginWeek3Viewed tinyint(1) NOT NULL DEFAULT 0,
    LoginWeek4Viewed tinyint(1) NOT NULL DEFAULT 0,
    LoginWeek5Viewed tinyint(1) NOT NULL DEFAULT 0,
    LoginWeek6Viewed tinyint(1) NOT NULL DEFAULT 0,
    LoginWeek7Viewed tinyint(1) NOT NULL DEFAULT 0,
    LoginWeek8Viewed tinyint(1) NOT NULL DEFAULT 0,
    LoginWeek9Viewed tinyint(1) NOT NULL DEFAULT 0,
    LoginWeek10Viewed tinyint(1) NOT NULL DEFAULT 0,
    MasterGamingViewed tinyint(1) NOT NULL DEFAULT 0,
    LaunchSportsNinjaViewed tinyint(1) NOT NULL DEFAULT 0,
    PlayEveryGameModeSnViewed tinyint(1) NOT NULL DEFAULT 0,
    BeatScoreSnAViewed tinyint(1) NOT NULL DEFAULT 0,
    BeatScoreSnBViewed tinyint(1) NOT NULL DEFAULT 0,
    BeatScoreSnCViewed tinyint(1) NOT NULL DEFAULT 0,
    LaunchMealCrusherViewed tinyint(1) NOT NULL DEFAULT 0,
    PlayEveryGameModeMcViewed tinyint(1) NOT NULL DEFAULT 0,
    BeatScoreMcAViewed tinyint(1) NOT NULL DEFAULT 0,
    BeatScoreMcBViewed tinyint(1) NOT NULL DEFAULT 0,
    BeatScoreMcCViewed tinyint(1) NOT NULL DEFAULT 0,
    
    WGContWeekStart TINYINT NOT NULL DEFAULT -1,
    WGContWeekCount TINYINT NOT NULL DEFAULT 0,
    
    PRIMARY KEY(StudentID),
    FOREIGN KEY (StudentID) REFERENCES student(StudentID)
) ENGINE=INNODB;
